---
parsers:
  javascript:
    enable_partials: yes

comment:
  layout: newheader, reach, files, components, diff, flags  # show component info in the PR comment
  hide_comment_details: true  # hide the comment details (e.g. coverage targets) in the PR comment

# Setting coverage targets
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        removed_code_behavior: adjust_base
        paths:
          - bin
          - lib
    patch:
      default:
        target: 80%

component_management:
  default_rules:  # default rules that will be inherited by all components
    statuses: []

flag_management:
  default_rules:  # the rules that will be followed for any flag added, generally
    carryforward: true
    statuses: []

# Do not consider zenko integration builds in coverage comparisons
flags:
  zenko-end2end-sharded:
    joined: false
  zenko-ctst-end2end-sharded:
    joined: false
